clear; close; clf;

%% Initialise Parameters for Digital Transmitter
fc = 4e6;      % Carrier Frequency
prf = 2e6;     % Pulse Repetition Frequency
n = 500;      % number of points
pulse_len = 1e-6;
t = linspace(0,pulse_len,n); % time
total = 100000;

%% Transmit Pulse Generator
pulse = square(2*pi*fc*t);

%% Frequency Divider
freq_div = fc/prf;
sig = pulse/freq_div;

for i = 1:length(sig)
    if sig(i) > 0
        sig(i) = 1;
    else
        sig(i) = 0;
    end
end

%% Transmit Gate
gate_len = 5e-6;
end_gate = round((gate_len/pulse_len)*n); % time
end_gate = end_gate + n;

%% Transmit
j = 0;
transmit = zeros(total, 1);
time = zeros(total, 1);

for i = 1:total
    if i < total
        time(i+1) = time(i) + t(2);
    end
    j = j+1;
    if j < n
        transmit(i) = sig(j);
    end
    if j == end_gate
        j = 1;
    end
end

figure(1)
plot(time, transmit)
xlabel('Time (s)')
ylabel('Amplitude (s)')
title('Transmitted Pulse Train')

%% create a data acquisition and add channels

d = daq('ni');
addinput(d, "Dev1","ai0","EdgeCount");
% addbidirectional(d,"Dev1","Port0/Line0:1","Digital");
% addbidirectional(d,"Dev1","Port0/Line2:3","Digital");
% [ch2,idx2] = addoutput(d,"Dev1","Port0/Line0:1","Digital");
addclock(d,"ScanClock","External","Dev1/PFI0")
d.Channels

%% Set the direction on all channels to output data
% set(d.Channels,"Direction","Output");

%% transmit pulse generated by transmitter as digital output data
% transmit = reshape(transmit, length(transmit)/2, 2);
% write(d,[1 0; 1 0]) 

%% Set the direction on all channels to input data
set(d.Channels, "Direction", "Input");

%% acquire the digital data
read(d, "OutputFormat","Matrix") % receive doppler shifted pulse and analyse accordingly